/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Especialidad;
import Entidades.Prestador;
import accesoData.EspecialidadData;
import accesoData.PrestadorData;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Usuario
 */
public class PrestadorVistas extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrestadorVistas
     */
    private PrestadorData pd = new PrestadorData();
    private EspecialidadData ed = new EspecialidadData();
    private Prestador prestadorActual = null;
    private Especialidad especialidad = null;
    
    
    public PrestadorVistas() {
        initComponents();

        jtNombre.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (!Character.isLetter(e.getKeyChar()) && e.getKeyChar() != ' ') {
                    e.consume();
                }
            }
        });
        
        jTApellido.addKeyListener(new KeyAdapter() {
        @Override
        public void keyTyped(KeyEvent e) {
            if (!Character.isLetter(e.getKeyChar()) && e.getKeyChar() != ' ') {
                e.consume();
            }
        }
    });
        jtEspecialidad.addKeyListener(new KeyAdapter() {
        @Override
        public void keyTyped(KeyEvent e) {
            if (!Character.isLetter(e.getKeyChar()) && e.getKeyChar() != ' ') {
                e.consume();
            }
        }
    });
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTDni = new javax.swing.JTextField();
        jTMatricula = new javax.swing.JTextField();
        jAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jREstado = new javax.swing.JRadioButton();
        jtEspecialidad = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Prestador");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("DNI:");

        jLabel5.setText("Matricula:");

        jLabel6.setText("Especialidad:");

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jTApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoActionPerformed(evt);
            }
        });

        jTDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDniActionPerformed(evt);
            }
        });

        jAgregar.setText("Agregar");
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado");

        jREstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jREstadoActionPerformed(evt);
            }
        });

        jtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEspecialidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAgregar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jREstado)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                            .addComponent(jTApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTMatricula, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(71, 71, 71)
                                                .addComponent(jButton3))
                                            .addComponent(jtEspecialidad, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(118, 118, 118))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jbBuscar)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jbBuscar))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jREstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgregar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
        // TODO add your handling code here:
        prestadorActual = null;
        especialidad = null;
        List<Especialidad> especialidadesCargadas = ed.listarEspecialidades();
        try{ 
        Integer dni = Integer.parseInt(jTDni.getText());
        // validar dni
        List<Prestador> prestadores = pd.listarPrestadores();
        for(Prestador elemento: prestadores){
            if(elemento.getDni()==dni){
                JOptionPane.showMessageDialog(this, "Dni asociado a otro prestador");
                return;
            }
        }
        
        Integer matricula = Integer.parseInt(jTMatricula.getText());
        // validar matricula
        for(Prestador elemento: prestadores){
            if(elemento.getMatricula()==matricula){
                JOptionPane.showMessageDialog(this, "Matricula asociada a otro prestador");
                return;
            }
        }
        
        String nombre = jtNombre.getText().toUpperCase();
        String apellido = jTApellido.getText().toUpperCase();
        String espec = jtEspecialidad.getText().toUpperCase();
        if(nombre.isEmpty() || apellido.isEmpty() || espec.isEmpty()){
            JOptionPane.showMessageDialog(this,"No puede haber campos vacios");
            return;
        }
        Boolean estado = jREstado.isSelected();
        Boolean validarEspec = false;
        
        for(Especialidad elem: especialidadesCargadas){
            if(elem.getEspecialidad().equalsIgnoreCase(espec)){
                validarEspec = true;
                break;            
            }       
        }
        
        if( validarEspec == false){
            especialidad = new Especialidad(espec);
            ed.guardarEspecialidad(especialidad);
            Especialidad especialidadNueva = ed.buscarEspecialidadPorNombre(espec);
            System.out.println(especialidadNueva.getIdEspecialidad());        
            prestadorActual = new Prestador(nombre,apellido,dni,estado,especialidadNueva,matricula);
            pd.guardarPrestador(prestadorActual);
        }else{
            especialidad = ed.buscarEspecialidadPorNombre(espec);
            
            prestadorActual = new Prestador(nombre,apellido,dni,estado,especialidad,matricula);
            pd.guardarPrestador(prestadorActual);
        }
        
        
       }catch(NumberFormatException nft){
           JOptionPane.showMessageDialog(this, "Ingresar un dato valido");
       }
       
       limpiar();
      
    }//GEN-LAST:event_jAgregarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        
        try{
            Integer dni = Integer.parseInt(jTDni.getText());
            
            prestadorActual = pd.buscarPrestadorPorDni(dni);
            if(prestadorActual!= null){
                jTApellido.setText(prestadorActual.getApellido());
                jtNombre.setText(prestadorActual.getNombre());
                String m = null;
                jTMatricula.setText(m.valueOf(prestadorActual.getMatricula()));
              //  String D = null;
            //    jTDni.setText(D.valueOf(prestadorActual.getDni()));
                EspecialidadData ed = new EspecialidadData();
                Especialidad es = null;
                es=ed.buscarEspecialidad(prestadorActual.getEspecialidad().getIdEspecialidad());
                
                jtEspecialidad.setText(es.getEspecialidad());
                jREstado.setSelected(prestadorActual.isActivo());            
              //  String i = null;
               // jtId.setText(i.valueOf(prestadorActual.getIdPrestador()));
                
                
            }
            
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
        }
        
        
        
    }//GEN-LAST:event_jbBuscarActionPerformed
        public void limpiar(){
            
        jtNombre.setText("");
        jTApellido.setText("");
        jTMatricula.setText("");
        jtEspecialidad.setText("");
        jTDni.setText("");
    //    jtId.setText("");
        jREstado.setSelected(false);
            
        }
    private void jTDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDniActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        /*   if(prestadorActual!= null){
            pd.eliminarPrestador(prestadorActual.getIdPrestador());
            prestadorActual = null;
        }else{
            JOptionPane.showMessageDialog(this, "Campo vacio");
        
        }*/
        try {
            Integer dni = Integer.parseInt(jTDni.getText());
            prestadorActual = null;

            prestadorActual = pd.buscarPrestadorPorDni(dni);
            if (prestadorActual != null) {
                pd.eliminarPrestador(prestadorActual.getIdPrestador());
            }
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(this, "Ingresar un dni");
        }

        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jREstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jREstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jREstadoActionPerformed

    private void jtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEspecialidadActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jtEspecialidadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        List<Especialidad> especialidadesCargadas = new ArrayList();
        especialidadesCargadas = ed.listarEspecialidades();
        if (prestadorActual != null) {
            prestadorActual.setApellido(jTApellido.getText().toUpperCase());
            prestadorActual.setNombre(jtNombre.getText().toUpperCase());
            prestadorActual.setDni(Integer.parseInt(jTDni.getText()));
            prestadorActual.setActivo(isSelected);
            prestadorActual.setMatricula(Integer.parseInt(jTMatricula.getText()));
            if (prestadorActual.getNombre().isEmpty() || prestadorActual.getApellido().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No puede haber campos vacios");
                return;
            }

            Boolean validarEspec = false;

            for (Especialidad elem : especialidadesCargadas) {
                if (elem.getEspecialidad().equalsIgnoreCase(jtEspecialidad.getText())) {
                    validarEspec = true;
                    break;
                }
            }

            if (validarEspec == false) {
                especialidad = new Especialidad(jtEspecialidad.getText().toUpperCase());
                ed.guardarEspecialidad(especialidad);
                Especialidad especialidadNueva = ed.buscarEspecialidadPorNombre(jtEspecialidad.getText().toUpperCase());
                prestadorActual.setEspecialidad(especialidadNueva);
                pd.modificarPrestador(prestadorActual);
            } else {
                especialidad = ed.buscarEspecialidadPorNombre(jtEspecialidad.getText());

                prestadorActual.setEspecialidad(especialidad);
                pd.modificarPrestador(prestadorActual);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Buscar un prestador");
        }
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoActionPerformed
    
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButton jREstado;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTMatricula;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JTextField jtEspecialidad;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
