/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Especialidad;
import Entidades.Prestador;
import accesoData.EspecialidadData;
import accesoData.PrestadorData;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Usuario
 */
public class PrestadorVistas extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrestadorVistas
     */
    private PrestadorData pd = new PrestadorData();
    private EspecialidadData ed = new EspecialidadData();
    private Prestador prestadorActual = null;
    private Especialidad especialidad = null;
    
    
    public PrestadorVistas() {
        initComponents();

        jtNombre.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (!Character.isLetter(e.getKeyChar()) && e.getKeyChar() != ' ') {
                    e.consume();
                }
            }
        });
        
        jTApellido.addKeyListener(new KeyAdapter() {
        @Override
        public void keyTyped(KeyEvent e) {
            if (!Character.isLetter(e.getKeyChar()) && e.getKeyChar() != ' ') {
                e.consume();
            }
        }
    });
        jtEspecialidad.addKeyListener(new KeyAdapter() {
        @Override
        public void keyTyped(KeyEvent e) {
            if (!Character.isLetter(e.getKeyChar()) && e.getKeyChar() != ' ') {
                e.consume();
            }
        }
    });
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTDni = new javax.swing.JTextField();
        jTMatricula = new javax.swing.JTextField();
        jAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jREstado = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtEspecialidad = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Prestador");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("DNI:");

        jLabel5.setText("Matricula:");

        jLabel6.setText("Especialidad:");

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jTApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoActionPerformed(evt);
            }
        });

        jTDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDniActionPerformed(evt);
            }
        });

        jAgregar.setText("Agregar");
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado");

        jREstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jREstadoActionPerformed(evt);
            }
        });

        jLabel8.setText("IdPrestador");

        jtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdActionPerformed(evt);
            }
        });

        jtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEspecialidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 321, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(25, 25, 25)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAgregar)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addGap(258, 258, 258))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jREstado)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtEspecialidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTDni, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTMatricula, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(25, 25, 25)
                                .addComponent(jbBuscar)
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(43, 43, 43)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jbBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jREstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgregar)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
        // TODO add your handling code here:
        prestadorActual = null;
        especialidad = null;
        List<Especialidad> especialidadesCargadas = ed.listarEspecialidades();
        try{ 
        Integer dni = Integer.parseInt(jTDni.getText());
        Integer matricula = Integer.parseInt(jTMatricula.getText());
        String nombre = jtNombre.getText();
        String apellido = jTApellido.getText();
        String espec = jtEspecialidad.getText();
        if(nombre.isEmpty() || apellido.isEmpty() || espec.isEmpty()){
            JOptionPane.showMessageDialog(this,"No puede haber campos vacios");
            return;
        }
        Boolean estado = jREstado.isSelected();
        for(Especialidad elem : especialidadesCargadas){
            if(elem.getEspecialidad().equals(espec)){
                especialidad = new Especialidad(elem.getIdEspecialidad()); // elem.getIdEspecialidad() es un int
                prestadorActual = new Prestador(nombre,apellido,dni,estado,especialidad,matricula);
                pd.guardarPrestador(prestadorActual);
                
                break;
            }else{
                especialidad = new Especialidad(espec);
                ed.guardarEspecialidad(especialidad);
                Especialidad especialidadNueva = new Especialidad();
                especialidadNueva = ed.buscarEspecialidadPorNombre(espec);
                prestadorActual = new Prestador(nombre,apellido,dni,estado,especialidadNueva,matricula);
                pd.guardarPrestador(prestadorActual);
                
                break;
            }
        }
        
        
        
        
       }catch(NumberFormatException nft){
           JOptionPane.showMessageDialog(this, "Ingresar un dato valido");
       }
        
      
    }//GEN-LAST:event_jAgregarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        
        try{
            Integer dni = Integer.parseInt(jTDni.getText());
            
            prestadorActual = pd.buscarPrestadorPorDni(dni);
            if(prestadorActual!= null){
                jTApellido.setText(prestadorActual.getApellido());
                jtNombre.setText(prestadorActual.getNombre());
                String m = null;
                jTMatricula.setText(m.valueOf(prestadorActual.getMatricula()));
              //  String D = null;
            //    jTDni.setText(D.valueOf(prestadorActual.getDni()));
                EspecialidadData ed = new EspecialidadData();
                Especialidad es = null;
                es=ed.buscarEspecialidad(prestadorActual.getEspecialidad().getIdEspecialidad());
                
                jtEspecialidad.setText(es.getEspecialidad());
                jREstado.setSelected(prestadorActual.isActivo());            
                String i = null;
                jtId.setText(i.valueOf(prestadorActual.getIdPrestador()));
                
                
            }
            
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
        }
        
        
        
    }//GEN-LAST:event_jbBuscarActionPerformed
        public void limpiar(){
            
        jtNombre.setText("");
        jTApellido.setText("");
        jTMatricula.setText("");
        jtEspecialidad.setText("");
        jTDni.setText("");
        jtId.setText("");
        jREstado.setSelected(false);
            
        }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        prestadorActual = null;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDniActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
     /*   if(prestadorActual!= null){
            pd.eliminarPrestador(prestadorActual.getIdPrestador());
            prestadorActual = null;
        }else{
            JOptionPane.showMessageDialog(this, "Campo vacio");
        
        }*/
     try{
        Integer dni = Integer.parseInt(jTDni.getText());
        prestadorActual = null;

        prestadorActual = pd.buscarPrestadorPorDni(dni);
        if (prestadorActual != null) {
            pd.eliminarPrestador(prestadorActual.getIdPrestador());
        }}catch(NumberFormatException n){
            JOptionPane.showMessageDialog(this, "Ingresar un dni");
        }

        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jREstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jREstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jREstadoActionPerformed

    private void jtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdActionPerformed

    private void jtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEspecialidadActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jtEspecialidadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        List<Especialidad> especialidadesCargadas = new ArrayList();
        especialidadesCargadas = ed.listarEspecialidades();
        if(prestadorActual != null){
            prestadorActual.setApellido(jTApellido.getText());
            prestadorActual.setNombre(jtNombre.getText());
            prestadorActual.setDni(Integer.parseInt(jTDni.getText()));
            prestadorActual.setActivo(isSelected);
            prestadorActual.setMatricula(Integer.parseInt(jTMatricula.getText()));
            for(Especialidad elem : especialidadesCargadas){
                if(elem.getEspecialidad().equalsIgnoreCase(jtEspecialidad.getText())){
                    prestadorActual.setEspecialidad(elem);
                    pd.modificarPrestador(prestadorActual);
                    break;
                }else{
                    especialidad = new Especialidad(jtEspecialidad.getText());
                    ed.guardarEspecialidad(especialidad);
                    Especialidad especialidadNueva = new Especialidad();
                    especialidadNueva = ed.buscarEspecialidadPorNombre(jtEspecialidad.getText());
                    prestadorActual.setEspecialidad(especialidadNueva);
                    pd.modificarPrestador(prestadorActual);
                    break;
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Buscar un prestador");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoActionPerformed
    
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButton jREstado;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTMatricula;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JTextField jtEspecialidad;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
